version: '3.8'

services:
  # Laravel Backend Service
  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    container_name: laravel-backend
    environment:
      - APP_ENV=local
      - APP_DEBUG=true
      - APP_KEY=base64:<Your-App-Key>
    volumes:
      - ./backend:/var/www/html
    ports:
      - "8000:8000"
    depends_on:
      - db

  # MySQL Database Service
  db:
    image: mysql:8
    container_name: mysql-db
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: laravel
      MYSQL_USER: laravel
      MYSQL_PASSWORD: laravel
    ports:
      - "3306:3306"
    volumes:
      - dbdata:/var/lib/mysql

  # React Frontend Service
  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    container_name: react-frontend
    volumes:
      - ./frontend:/usr/src/app
    ports:
      - "3000:3000"
    stdin_open: true
    tty: true

volumes:
  dbdata:
